export const allEvents = [
  {
    id: 1,
    title: "best event",
    description: "The best event.",
    goal: 200,
    image: "https://via.placeholder.com/300.jpg",
    is_open: true,
    date_created: "2020-03-20T14:28:23.382748Z",
    slug: "best-event",
    owner: 1,
    category: "Charity",
    region: "World",
  },
  {
    id: 3,
    title: "The third event",
    description: "The best event.",
    goal: 900,
    image: "https://via.placeholder.com/200.jpg",
    is_open: true,
    date_created: "2020-03-20T14:28:23.382748Z",
    slug: "the-third-event",
    owner: 1,
    category: "Charity",
    region: "World",
  },
  {
    id: 4,
    title: "The fourth event",
    description: "The best event.",
    goal: 900,
    image: "https://via.placeholder.com/200.jpg",
    is_open: true,
    date_created: "2020-03-20T14:28:23.382748Z",
    slug: "the-fourth-event",
    owner: 1,
    category: "Charity",
    region: "World",
  },
];

export const oneEvent = {
  id: 1,
  title: "best event",
  description: "The best event.",
  goal: 200,
  image: "https://via.placeholder.com/300.jpg",
  is_open: true,
  date_created: "2020-03-20T14:28:23.382748Z",
  slug: "best-event",
  owner: 1,
  category: "Charity",
  region: "World",
  pledges: [
    {
      id: 2,
      amount: 50,
      comment: "Let's have a look",
      anonymous: true,
      supporter: 2,
      event: 1,
    },
    {
      id: 3,
      amount: 350,
      comment: "I really want",
      anonymous: false,
      supporter: 1,
      event: 1,
    },
    {
      id: 4,
      amount: 350,
      comment: "I really want",
      anonymous: false,
      supporter: 1,
      event: 1,
    },
    {
      id: 5,
      amount: 250,
      comment: "I really want",
      anonymous: false,
      supporter: 1,
      event: 1,
    },
    {
      id: 6,
      amount: 3150,
      comment: "I really want",
      anonymous: false,
      supporter: 1,
      event: 1,
    },
    {
      id: 7,
      amount: 33333150,
      comment: "",
      anonymous: false,
      supporter: 1,
      event: 1,
    },
  ],
};
